name: baker
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.10.2
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.3
  - pandoc=2.11
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0
  - pycodestyle=2.6.0
  - pygments=2.7.2
  - pypandoc=1.5
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.12
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.0
  - setuptools=50.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - astroid==2.4.2
    - cffi==1.14.3
    - chardet==3.0.4
    - cryptography==3.2.1
    - idna==2.10
    - isort==5.6.4
    - jieba==0.42.1
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - numpy==1.16.4
    - objgraph==3.5.0
    - paddlepaddle-tiny==1.6.1
    - pdfminer-six==20201018
    - protobuf==3.14.0
    - pycparser==2.20
    - pylint==2.6.0
    - python-graphviz==0.16
    - requests==2.25.0
    - sortedcontainers==2.3.0
    - toml==0.10.2
    - typed-ast==1.4.1
    - urllib3==1.26.2
    - wrapt==1.12.1
